# Use lightweight Python base
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Create persistent data directory
VOLUME ["/data"]

# Expose port
EXPOSE 5000

# Start Flask
CMD ["python", "hitcounter.py"]